# fly.toml app configuration file generated for kopitiam-run on 2026-02-13T23:05:23+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kopitiam-run'
primary_region = 'sin'

[[mounts]]
  source = 'kopitiam_data'
  destination = '/data'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.http_checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '15s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
